winget uninstall 'Mail and Calendar'
winget uninstall 'Groove Music'
winget uninstall 'Your Phone'
winget uninstall 'Xbox Game Speech Window'
winget uninstall 'Xbox Identity Provider'
winget uninstall 'Xbox Game Bar'
winget uninstall 'Xbox Game Bar Plugin'
winget uninstall 'Xbox'
winget uninstall 'Xbox TCUI'
winget uninstall 'Windows Maps'
winget uninstall 'Feedback Hub'
winget uninstall 'Windows Calculator'
winget uninstall 'Microsoft Photos'
winget uninstall 'Microsoft Pay'
winget uninstall 'Skype'
winget uninstall 'Microsoft People'
winget uninstall 'OneNote'
winget uninstall 'Mixed Reality Portal'
winget uninstall 'Microsoft Sticky Notes'
winget uninstall 'Microsoft Solitaire Collection'
winget uninstall 'Office'
winget uninstall '3D Viewer'
winget uninstall 'Paint 3D'
winget uninstall 'Microsoft Tips'
winget uninstall 'Get Help'
winget uninstall 'MSM Weather'
winget uninstall 'MSN Weather'
winget uninstall 'Cortana'
winget uninstall 'Films & TV'
winget uninstall "Snip & Sketch"
winget uninstall "Movies & TV"
winget uninstall "Microsoft Update Health Tools"